name: StrikeCommands
version: '${project.version}'
author: Siwoo
website: siwoo.lol, siwoo.club
main: club.siwoo.strikecommands.StrikeCommands
commands:
  forcewin:
    usage: /forcewin (fight/round)
    description: "(Admin Only) Forces to win the fight."